### ISSUE TITLE
Phần Testimonials

### ISSUE THREAD

**Issue by duongnt9x** [minhbeo1997/ducminh.github.io#3]
- Font chữ đoạn LIPSUM và 33 years old vẫn sai
- Đoạn văn cần tăng padding lên và căn justify
<img width="437" alt="screen shot 2017-07-17 at 09 10 45" src="https://user-images.githubusercontent.com/5635847/28253824-a721ddf2-6ad1-11e7-9e34-fbc23a920aa9.png">

**Comment by minhnd-97** [comment]
done

**Comment by duongnt9x** [comment]
https://www.w3schools.com/cssref/css3_pr_text-justify.asp  @minhbeo1997  đọc cái này
