### ISSUE TITLE
Trên màn ip5, ip6, header bị xuống dòng

### ISSUE THREAD

**Issue by duongnt9x** [minhbeo1997/ducminh.github.io#7]
<img width="376" alt="screen shot 2017-07-17 at 09 29 55" src="https://user-images.githubusercontent.com/5635847/28254019-39a593c0-6ad3-11e7-958a-d437e2665a75.png">
<img width="320" alt="screen shot 2017-07-17 at 09 29 18" src="https://user-images.githubusercontent.com/5635847/28254018-3994a3bc-6ad3-11e7-85c8-adcb0ffbf234.png">

**Comment by minhnd-97** [comment]
done
