### ISSUE TITLE
3 dấu chấm ở dưới title ở mỗi màn hình một khác 

### ISSUE THREAD

**Issue by duongnt9x** [minhbeo1997/ducminh.github.io#8]

**Comment by minhnd-97** [comment]
là sao chịu ?

**Comment by minhnd-97** [comment]
ok done em fix lại chấm trên màn hình điện thoại rồi

**Comment by duongnt9x** [comment]
@minhbeo1997  cái 3 dấu chấm này bị trên tất cả các màn hình mà.
E cắt 1 cái hình có đủ cả 3 dấu chấm chứ đừng code từng dấu 1 như thế này, vừa mất công mà vừa k đẹp
