### ISSUE TITLE
Phần testimonial trên mobile 

### ISSUE THREAD

**Issue by duongnt9x** [minhbeo1997/ducminh.github.io#9]
Nếu chưa làm được slider thì bỏ hiệu ứng hover đi vì:
- trên mobile k có hover 
- các nội dung sẽ bị đè lên nhau
<img width="316" alt="screen shot 2017-07-17 at 09 39 39" src="https://user-images.githubusercontent.com/5635847/28254121-fe97d742-6ad3-11e7-9223-05f0e6198ccb.png">

**Comment by minhnd-97** [comment]
done
